# GolangCI-Lint v2.5 Configuration for Born ML Framework
# Documentation: https://golangci-lint.run/docs/configuration/
# Copied from: github.com/born-ml/born/cortex (reference project)
# AGGRESSIVE CONFIGURATION - Catches more issues during development

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Enable comprehensive set of linters for production-quality code
  enable:
    # Code quality and complexity
    - gocyclo       # Check cyclomatic complexity
    - gocognit      # Check cognitive complexity
    - funlen        # Check function length
    - maintidx      # Maintainability index
    - cyclop        # Check cyclomatic complexity (alternative)
    - nestif        # Reports deeply nested if statements

    # Bug detection
    - govet         # Standard Go vet (includes copylocks!)
    - staticcheck   # Comprehensive static analysis
    - errcheck      # Check that errors are handled
    - errorlint     # Check error wrapping
    - gosec         # Security issues
    - nilnil        # Check that functions don't return nil both ways
    - nilerr        # Check nil error returns
    - nilnesserr    # Check nil error returns patterns
    - ineffassign   # Detect ineffectual assignments

    # Code style and consistency
    - misspell      # Check for misspelled words
    - whitespace    # Check for trailing whitespace
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Detect unused function parameters

    # Naming conventions
    - errname       # Check error naming conventions
    - revive        # Fast, configurable, extensible linter

    # Performance
    - prealloc      # Find slice declarations that could be preallocated
    - bodyclose     # Check HTTP response bodies are closed
    - makezero      # Find slice declarations with non-zero initial length

    # Code practices
    - goconst       # Find repeated strings that could be constants
    - gocritic      # Comprehensive code checker
    - goprintffuncname  # Check printf-like function names
    - nolintlint    # Check nolint directives are used correctly
    - nakedret      # Checks for naked returns

    # Comments and documentation
    - godot         # Check comments end in periods
    # godox disabled - TODO comments are acceptable during development

    # Additional quality checkers
    - dupl          # Detect duplicate code
    - dogsled       # Check for assignments with too many blank identifiers
    - durationcheck # Check for two durations multiplied together

  settings:
    govet:
      # EXPLICITLY ENABLE copylocks to catch mutex copying issues
      enable:
        - copylocks
      # Disable fieldalignment (memory optimization not critical)
      disable:
        - fieldalignment

    gocyclo:
      # Lower threshold for production code
      min-complexity: 15

    cyclop:
      # Max complexity
      max-complexity: 15

    funlen:
      # Allow reasonably long functions for routing logic
      lines: 120
      statements: 60

    gocognit:
      # Cognitive complexity threshold
      min-complexity: 20

    misspell:
      locale: US

    nestif:
      # Max nesting level
      min-complexity: 4

    revive:
      # Enable important rules for code quality
      rules:
        - name: var-naming
        - name: exported
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    gocritic:
      # Enable important checks
      enabled-tags:
        - diagnostic
        - style
        - performance

      # Disable overly opinionated/experimental checks
      disabled-checks:
        - commentFormatting  # Too opinionated about comment style
        - whyNoLint          # We document nolints when needed
        - unnamedResult      # Named results can reduce readability
        - commentedOutCode   # False positives on test data comments

      settings:
        hugeParam:
          # Tensor structures can be large (multi-dimensional arrays)
          # Default is 80 bytes, allow larger structs for ML operations
          sizeThreshold: 256

  # Exclusions (v2 structure: linters.exclusions.rules)
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - cyclop
          - funlen
          - maintidx
          - errcheck
          - gosec
          - goconst
          - dupl
          - nestif

      - path: ".*\\.pb\\.go"  # Generated files
        linters:
          - revive
          - gocritic

      # cmd/ and scripts/ - utility programs can be less strict
      - path: (cmd|scripts)/.*\.go
        linters:
          - gocognit     # Command-line tools can be complex
          - nestif       # CLI logic acceptable
          - funlen       # Main functions can be longer
          - gocyclo      # CLI complexity acceptable
          - cyclop       # CLI complexity acceptable
          - godot        # Command output formatting
          - gosec        # CLI file operations acceptable
          - gocritic     # CLI patterns acceptable

      # internal/tensor/mock - naive test backend
      - path: internal/tensor/mock\.go
        linters:
          - funlen       # Mock functions can be longer
          - gocyclo      # Mock implementations complexity
          - cyclop       # Test code complexity acceptable
          - nestif       # Test nesting acceptable
          - gocognit     # Mock complexity acceptable

      # internal/backend/cpu/ops_* - type-specific implementations
      - path: internal/backend/cpu/ops_(float32|float64|int)\.go
        linters:
          - dupl         # Expected duplication for type-specific implementations

      # internal/backend/cpu - type-specific implementations for new operations (TASK-019)
      - path: internal/backend/cpu/(scalar|comparison|boolean|activation|math|reduce|shape|conversion)\.go
        linters:
          - dupl         # Expected duplication for type-specific implementations (float32, float64, int32, int64, uint8, bool)

      # Conv2D/MaxPool2D - separate float32/float64 for performance (avoid interface overhead)
      - path: internal/backend/cpu/(conv2d|maxpool2d)\.go
        linters:
          - dupl         # Intentional type-specific implementations
          - gocognit     # im2col and pooling algorithms inherently complex
          - gocritic     # Math notation (N, H, W, CIn, COut) for clarity

      # Manipulation operations - type-specific implementations for performance
      - path: internal/backend/cpu/manipulation\.go
        linters:
          - dupl         # Intentional duplication for type-specific implementations (float32, float64, int32, int64, uint8, bool)
          - gocyclo      # Cat/Chunk algorithms inherently complex with tensor indexing
          - cyclop       # Complex tensor manipulation acceptable

      - path: internal/autodiff/ops/(conv2d|maxpool2d)\.go
        linters:
          - dupl         # Intentional float32/float64 separation
          - gocognit     # Backward pass algorithms inherently complex
          - gocritic     # Math notation (N, H, W, CIn, COut) for clarity

      # Backend types - stuttering is acceptable in Go (e.g., cpu.CPUBackend, autodiff.AutodiffBackend)
      - path: internal/backend/cpu/backend\.go
        text: "type name will be used as cpu.CPUBackend"
        linters:
          - revive

      - path: internal/autodiff/autodiff\.go
        text: "type name will be used as autodiff.AutodiffBackend"
        linters:
          - revive

      # Examples - demonstration code can be verbose
      # Multiple main() functions in examples/ is expected (each is standalone)
      - path: examples[/\\].*\.go
        linters:
          - errcheck     # Examples may skip error handling for clarity
          - errorlint    # Examples may use %v instead of %w
          - funlen       # Example functions can be longer
          - gocyclo      # Example complexity acceptable
          - cyclop       # Example complexity acceptable
          - gocognit     # Example complexity acceptable
          - nestif       # Example nesting acceptable
          - typecheck    # Skip typecheck for examples (multiple main)
          - godot        # Example comments don't need periods
          - revive       # Examples don't need full documentation
          - gosec        # Examples may have security warnings
          - gocritic     # Example patterns may differ

issues:
  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0

  # Don't hide new issues in existing files
  new: false
